---
- name: who am i
  command: whoami
  register: whoami

- debug:
    msg: "I am {{whoami.stdout}}"

- name: Get System Info
  # command: "dpkg --print-architecture"
  shell: >
    echo {\"arch\": \"$(dpkg --print-architecture)\", \"distro\": \"$(lsb_release -cs)\", \"release\": \"$(lsb_release -rs)\"}
  register: result

- name: sudo dpkg --configure -a
  command: dpkg --configure -a
  become: yes
  # shell: >
  #   echo {\"arch\": \"$(dpkg --print-architecture)\", \"distro\": \"$(lsb_release -cs)\", \"release\": \"$(lsb_release -rs)\"}
  

- name: convert result
  set_fact:  
    system_info: "{{ result.stdout|from_json }}"

- name: user config {{user_account.home}}/.bashrc
  stat:
    path: "{{user_account.home}}/.bashrc"
  register: bashrc

