id_rsa_file:  /home/marcospcruz/.ssh/id_rsa.pub
# passphrase: "changeit"
# root_password: "password"
timezone: "America/Sao_Paulo"
raspberry:
  system:
    firmware:
      file:
        content: "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 net.ifnames=0 dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait"
        path: /boot/firmware/cmdline.txt
state:
  present: "present"
  absent: "absent"    
# nodes: all
# mkpasswd --method=sha-512
user_account:
  name: marcospcruz
  groups: ['marcospcruz','sudo','libvirt']
  password: "{{password}}"
  home: /home/marcospcruz
  

apt:
  modules:
    packages:
      - pulseaudio-module-bluetooth 
      - pulseaudio
  rockpi:
    packages:
    # - rockchip-fstab 
    - rockchip-overlay
    - linux-4.4-latest # kernel version(>=4.4.154.100)
    - broadcom-wifibt-firmware
    - rockpi4-dtbo
  packages: 
  - gnupg2
  - net-tools  
  - vim
  - curl
  - dbus-user-session
  - glib-networking 
  - libgtk-3-common
  # - python3 
  # - kvm 
  # - libvirt-bin 
  - virt-manager
  # - ubuntu-vm-builder
  - bridge-utils 
  - cpu-checker 
  - libvirt-clients 
  - libvirt-daemon 
  - libvirt-daemon-system
  - aptitude
  - qemu 
  - qemu-kvm
  - hdparm
  - iperf
  - mtr-tiny
  - bridge-utils
  - socat
  - jq
  - dnsutils
  - ca-certificates 
  - apt-transport-https
  - gnupg   
  - software-properties-common
  - uidmap  
  - snapd
  - cgroup-lite
  - conntrack 
  
k8s:
  version: "v1.23.4-rc.0"
docker:
  # devicemapper or overlay2
  storage_driver: devicemapper
  # storage_driver: overlay2
  expose_tcp: true
  # version: "17.12.0~ce-0~ubuntu"
  version: "5:20.10.16~3-0~ubuntu-focal"
  packages: 
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  user_env_vars:
  - 'export XDG_RUNTIME_DIR=/run/user/$UID'
  - 'export PATH=/usr/bin:$PATH'
  - 'export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock'
                                            
# https://wiki.radxa.com/Rockpi4/Ubuntu
rockpi:
  h2_intfc_conf:
# I2C
# Modify file /boot/hw_intfc.conf. Set "on" to enable the optional hardware interfaces while set "off" to disable.
  - intfc: 
    - i2c2: "intfc:i2c2=on"
    - i2c6: "intfc:i2c6=on"
    - i2c7: "intfc:i2c7=on"
# PWM
# Modify file /boot/hw_intfc.conf. Set "on" to enable the optional hardware interfaces while set "off" to disable.
    - pwm0: "intfc:pwm0=on"
    - pwm1: "intfc:pwm1=on"
# SPI
# Modify file /boot/hw_intfc.conf. Set "on" to enable the optional hardware interfaces while set "off" to disable.
    - spi1: "intfc:spi1=on"
    - spi2: "intfc:spi2=on"
    - dtoverlay:    
      - devspi1: "intfc:dtoverlay=devspi1"
      - devspi2: "intfc:dtoverlay=devspi2"
# UART
# Modify file /boot/hw_intfc.conf. Set "on" to enable the optional hardware interfaces while set "off" to disable.
    - uart2: "intfc:uart2=on"
    - uart4: "intfc:uart4=on"