all:
  children:
    master:
      hosts:
        raspberry-4-node-master:
          user: "{{ansible_remote_user}}"
          # user_passwd: "{{host_user_passwd}}" ansible vault
          user_password: "{{password}}"
          ssh_pub_key:  "{{ ssh.pub_key_path }}"
          ansible_become_pass: "{{ password }}"
          cfg_static_network: false
    nodes:
      hosts:
        raspberry-4-node-2:
          user: "{{ansible_remote_user}}"
          user_password: "{{password}}"
          ssh_pub_key: "{{ ssh.pub_key_path  }}"
          ansible_become_pass: "{{ password }}"
          cfg_static_network: false      
        rockpi-4b:
          user: "{{ansible_remote_user}}"
          user_password: "{{password}}"
          ssh_pub_key: "{{ ssh.pub_key_path  }}"
          ansible_become_pass: "{{ password }}"
          cfg_static_network: false
        # localhost:
        #   user: "{{ansible_remote_user}}"
        #   user_password: "{{password}}"
        #   ssh_pub_key: "{{ ssh.pub_key_path  }}"
        #   ansible_become_pass: "{{ password }}"
        #   cfg_static_network: false
              
  vars:
    ansible_remote_user: ubuntu
    home: /home/{{ansible_remote_user}}
    # ssh:
    #   pub_key_path:
    timezone: "America/Sao_Paulo"
