- name: Reset System Defaults
  hosts: all
  gather_facts: yes
  remote_user: "{{ansible_remote_user}}"
  become: true
  become_method: sudo
  vars_files:
    - config.yml
  

  roles:
    - defaults
    - reset_system

