- hosts: raspberry-node-2
  gather_facts: yes
  remote_user: "{{ansible_remote_user}}"
  become: true
  become_method: sudo
  become_user: "{{user_account.name}}"
  vars_files:
    - config.yml
  vars:
    # gofabric8_start: "gofabric8 start --vm-driver=kvm" ## not supported
    gofabric8_start: "gofabric8 start"

  roles:
  - defaults
  - start_fabric8