- name: restart docker
  service: name=docker enabled=yes state=restarted

- name: stop docker
  service: 
    name: docker 
    enabled: yes 
    state: stopped

- name: restart kubelet
  service: name=kubelet enabled=yes state=restarted
