# kind: MasterConfiguration
# # kind: ClusterConfiguration
# # apiVersion: v1.11
# apiVersion:  kubeadm.k8s.io/v1beta2
# networking:
#   # podSubnet: "{{ network.pod_subnet }}"
#   serviceSubnet: "{{ network.service_subnet }}"
# controllerManagerExtraArgs:
#   horizontal-pod-autoscaler-use-rest-clients: "true"
#   horizontal-pod-autoscaler-sync-period: "10s"
#   node-monitor-grace-period: "10s"
# apiServerExtraArgs:
#   runtime-config: "api/all=true"
# # kubernetesVersion: "v1.24.0"
# kubernetesVersion: "v1.9.0"
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"