---
- name: Remove {{docker.packages}}
  apt:
    name: "{{docker.packages}}"
    # name: ['cgroupfs-mount','cgroup-lite','docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin','docker-engine']
    # force: yes
    state: absent
    # force_apt_get: yes
    autoremove: yes
    purge: yes
    # autoclean: yes
  # ignore_errors: True
  register: apt_result

- name: dockerd-rootless-setuptool.sh uninstall --force
  command: dockerd-rootless-setuptool.sh uninstall --force
  become_user: "{{user_account.name}}"
  ignore_errors: True

- debug:
    msg: "{{apt_result}}" 

- name:  remove docker files
  file:
    state: absent
    path: "{{item}}"
  with_items:
  - "/etc/apt/keyrings"
  - "/etc/apt/sources.list.d/docker.list"
  - "/etc/docker/daemon.json"
  - "/var/run/docker.sock"
  - "/lib/systemd/system/docker.service"
  - "/var/lib/docker"
  - "/var/lib/containerd"
  - "$XDG_RUNTIME_DIR"
- name: user config {{user_account.home}}/.bashrc
  stat:
    path: "{{user_account.home}}/.bashrc"
  register: bashrc
- debug: 
    msg: "{{bashrc}}"
- name: update bashrc
  lineinfile: 
    dest: "{{bashrc.stat.path}}"
    regexp: '{{item}}'
    line: "{{item}}"
    state: absent
  # with_items: "{{docker.user_env_vars}}"
  with_items: "{{docker.user_env_vars}}"
  when: "bashrc.stat.exists"
  

- name: Delete group
  group:
    # name: "{{ user_account.name }}"
    name: docker
    state: absent
  become: yes
  # when: "'root' in whoami.stdout"