
- name: Kubernetes Tools | Remove Packages
  apt:
    # name: "{{ item }}"
    name: ['kubelet', 'kubeadm', 'kubectl', 'kubernetes-cni', 'conntrack','cri-tools']
    force: yes
    state: absent
    autoremove: yes
    purge: yes
 

- name: Kubernetes Tools | remove files
  file:
    state: absent
    path: "{{item}}"
  with_items:
  - /etc/profiles.d/kubernetes.sh
  - /usr/local/bin/gofabric8