---
- name: who am i
  command: whoami
  register: whoami

- name: Remove {{apt.packages}}
  include_tasks: defaults.yml

- debug:
    msg: "I am {{whoami.stdout}}"

- name: Remove Kubernetes Tools
  include_tasks: kubernetes.yml


- name: Remove Docker
  include_tasks: docker.yml


- name: Remove podman
  include_tasks: podman.yml



- name: Wait for server to restart
  reboot:
    reboot_timeout: 3600
  async: 600
  poll: 5
  
- name: Remove user
  include_tasks: user.yml