---
# - name: podman machine
#   include_tasks: podman-machine.yml

- name:  Check gofabric8
  shell: >
    find $(which gofabric8) |wc -l
  register: fabric_output


- name: Run {{gofabric8_start}}
  command: "{{gofabric8_start}}"
  when: "'1' == fabric_output.stdout"
  register: rc_status
  ignore_errors: yes
  async: 600
  poll: 5

- debug:
    msg: "{{item}}"
  with_items: rc_status.stderr_lines

- name:  minikube delete
  command: "minikube delete"
  when: "'1' == fabric_output.stdout"  
  ignore_errors: yes
  async: 600
  poll: 5



- name:  minikube start
  # command: "{{user_account.home}}/.fabric8/bin/minikube start --memory=1848mb --driver=kvm --kubernetes-version={{k8s.version}}"
  # command: "{{user_account.home}}/.fabric8/bin/minikube start --memory=1848mb --kubernetes-version={{k8s.version}}"
  command: "{{user_account.home}}/.fabric8/bin/minikube start --driver {{vm_driver}} --container-runtime=containerd"
  when: "'1' == fabric_output.stdout"  
  async: 600
  poll: 5
  ignore_errors: yes
  register: minikube_status


- name:  minikube update-context
  command: "{{user_account.home}}/.fabric8/bin/minikube update-context"
  when: "'1' == fabric_output.stdout"  
  async: 600
  poll: 5
  ignore_errors: yes

- name:  Trying once again {{gofabric8_start}}
  command: "{{gofabric8_start}}"
  when: "'1' == fabric_output.stdout"
  register: rc_status
  # ignore_errors: yes